notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: Zs9XFFUN7ObuOws3/VnY/9HISpErdf/mQGPO5BdEe9A0Oywy6hCcxtG3c6UYjHyZdctFPdVjpPEOni2yqBUweY3y+Peud3tqhgLv+DI2KzbJbU2PVXuL4UmkpZ8DChuBVFQXNR7mPC7r+mHVsS+IxEDJIQg5Td/Za4/uelEzNmw0XMFnBUysoGjUU90ipERV7yl7czCi6r5INl9I7UlofY92J/rB7IT3ZZ/bK/haQa6M65VztVOtOMhve6davgXOQVv7WqeL2ntZ9w9+b0W8+eFTsqdjuqc80qf/xeJL2TQ6KWL4jcavdUFjoj82vLbu81o/W+XMVRBn6olGuRLrwNG5Ua30ZHrLF4GEN9SiqK4bmuoLVKqcLCDFUen/fO0Wd9S3FcYuwV4jGP38OnfzASlTtwZrCuCoUoHFd2Tw88IiA7707m0a1OTyhPrA/sfx+2yTdxZxFSc1EymZDf/iNyO2ANSZpb45UXNQZPGQuWiRWF+b3d+HLuGnidw1YlqyX1onD5Rjvm41zuSBKeSUEtWecBLkpNJ6JHF3VwbTbVfu+z4ph2zfpO9+Y5hGHK1FghcfnGKmpaw/N8naqa7soyx5QyoAYLC0gBeQXsmHmv3PeLMA+5zSD7OQ7vrAzjh32R7NwU8gq2B2yw0qX5laFw27tPRaqEbmf5thCORwwqk=
  api_key:
    secure: Orn311yJmblP6zIG4TF5OcwehL70D+pcBOKM6Ev6F1DKHQJK0Al4Rfiq/4zpucX2gG+XnQxgZmHnVamOjN7CCyTR3fV1JQDTpsVHAhy6kPuD/BUtDb0Fsx8wJY9nUPdL9X6PlmIaqHdK78gdIObaV4O6iTZ0zUJ9ICtbJejub9MkK2xJDX4LvXwwJti+ht9HfIJnqGowthaOUWeIXP9cbcGtRUrGasgW97pt7Tov4A7v1WPNbgl33Y0zKXHQ7pEdmf56A+ACi9uzL5ydy2yehBFGJiV4NHx2e/7E/G3J/jWrrDIB9Dzdi5u0Ije/s/YqRML0fQA6kyLauSPKrQuaJLq6tB6iPjsFYXqCuRQWfdDjzODxOcnFNRY7K90k/xS5YQ3kcgO/h0PkbVNqP+DPWVWar2b0UZtAbpI2xDN0KLNTWBSEwc7zI0FLHLhWutCPOhF97Uj9kQRCDx9MXHRJOnfnwFI2zrmv678BSp2HzRwQG5d8j89WfjdLtaZj162T+Bk27bgqJ8ZtEubULbVh0LZNnuyT0S1GGCJ+jnplbk/SnqJsM91j6dVU0i1asMhDI5JfeTKKcwETDawZz5alPVEmcqSO1X3AODv4GhjcanskDclO2QqBsogW4titJoHpJWIQkjzBE/XwIRje++pyVVsQEKMB0ajXTrHjBQca780=
